### ISSUE TITLE
Add support for Dotty

### ISSUE THREAD

**Issue by Sciss** [scala-stm/scala-stm#9]

**Comment by Sciss** [comment]
please see [dotty branch](https://github.com/scala-stm/scala-stm/tree/dotty). Mostly done except for the issue that `OptManifest` does not seem to work (why?)

**Comment by Sciss** [comment]
See https://github.com/lampepfl/dotty/issues/9482

**Comment by Sciss** [comment]
The only problematic method is

```scala
object Ref {
  def make[A]()(implicit om: OptManifest[A]): Ref[A] = (om match {
    case m: ClassTag[_] => m.newArray(0).asInstanceOf[AnyRef] match {
      // these can be reordered, so long as Unit comes before AnyRef
      case _: Array[Boolean] => apply(false)
      case _: Array[Byte]    => apply(0 : Byte)
      case _: Array[Short]   => apply(0 : Short)
      case _: Array[Char]    => apply(0 : Char)
      case _: Array[Int]     => apply(0 : Int)
      case _: Array[Float]   => apply(0 : Float)
      case _: Array[Long]    => apply(0 : Long)
      case _: Array[Double]  => apply(0 : Double)
      case _: Array[Unit]    => apply(())
      case _: Array[AnyRef]  => factory.newRef(null.asInstanceOf[A])(m.asInstanceOf[ClassTag[A]])
    }
    case _ => factory.newRef(null.asInstanceOf[Any])(implicitly[ClassTag[Any]])
  }).asInstanceOf[Ref[A]]
}
```
because the `apply` constructor is already overloaded for all primitives, so in practice you get optimisation from `Ref(123)` and it would be a rare case that the user carries around a `ClassTag`. Or what do you think?

Also, having to construct an array is also not too nice and efficient.

**Comment by Sciss** [comment]
We could also just drop this optimisation in Scala-STM, as `Ref.make[Int]` is rather rare, and one could recommend to the user to use `Ref(0)` instead. That way we can drop `OptManifest` from `make`, and it will simply make `AnyRef` references. What do you think @nbronson ?

**Comment by nbronson** [comment]
Thanks for working on this! I think dotty support is more important than this optimization. Perhaps we should deprecate the method if it is now less optimal than before?

**Comment by Sciss** [comment]
Looking at this:
```scala
  private def newPrimitiveRef[A](initialValue: A, m: AnyValManifest[_]): Ref[A] = {
    (m.newArray(0).asInstanceOf[AnyRef] match {
      case _: Array[Int]     => apply(initialValue.asInstanceOf[Int])
      case _: Array[Boolean] => apply(initialValue.asInstanceOf[Boolean])
      case _: Array[Byte]    => apply(initialValue.asInstanceOf[Byte])
      case _: Array[Short]   => apply(initialValue.asInstanceOf[Short])
      case _: Array[Char]    => apply(initialValue.asInstanceOf[Char])
      case _: Array[Float]   => apply(initialValue.asInstanceOf[Float])
      case _: Array[Long]    => apply(initialValue.asInstanceOf[Long])
      case _: Array[Double]  => apply(initialValue.asInstanceOf[Double])
      case _: Array[Unit]    => apply(initialValue.asInstanceOf[Unit])
    }).asInstanceOf[Ref[A]]
  }
```
is there a reason why the manifest is needed at all? Would it not be sufficient (and more efficient?) to just match the `initialValue`? Like
```scala
  private def newPrimitiveRef[A](initialValue: A): Ref[A] = initialValue match {
    case v: Int     => apply(v)
    case v: Boolean => apply(v)
    case v: Byte    => apply(v)
    case v: Short   => apply(v)
    case v: Char    => apply(v)
    case v: Float   => apply(v)
    case v: Long    => apply(v)
    case v: Double  => apply(v)
    case v: Unit    => apply(v)
  }
```
?

**Comment by nbronson** [comment]
This structure led to much better codegen by HotSpot at the time. It's not relevant to Dotty, and might have been obviated by changes to Scala or improvements to the JVM.

**Comment by Sciss** [comment]
I see – well in <= 2.13, it remains unchanged anyways.
